### ISSUE TITLE
How to connect inputs and outputs

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_ontology#84]
```python
def get_structure(element: str) -> u(Atoms, otype=("hasElement", "input.element"), label="Computational Sample")
```

Currently, we don't have a way to tell how inputs and outputs are ontologically connected, for example `structure` and `element` in the function above. On possibility is to make use of `otype` or introduce `triple` to explicitly state their relationship. It looks, however, super redundant, because in the end we will provide with URIs and therefore it's sort of obvious that the input element is the element of the output structure. At the same time, I also think the danger is super large if we implicitly assume there's a relationship between the two. I guess the best is still to have to state it explicitly, but maybe we can come up with a better syntax, in order not to have to write so much.

**Comment by samwaseda** [comment]
I made my first prototype for the super simple case: There's a structure for the input and some output value:

# Parser

```python
from rdflib import Graph, Literal, RDF, RDFS, URIRef, Namespace
from semantikon.converter import parse_input_args, parse_output_args

EX = Namespace("http://example.org/")

def create_node(graph, namestring, classtype, label=None):
    item = URIRef(namestring)
    if len(list(g.triples((item, None, None)))) == 0:
        graph.add((item, RDF.type, classtype))
        if label is not None:
            graph.add((item, RDFS.label, Literal(label)))
    return item, graph

def add_calculated_quantity(graph, sample, propertyname, value, units=None, EX=EX):
    prop, graph = create_node(graph, f"{sample}_{propertyname}", EX.CalculatedProperty)
    graph.add((sample, EX.hasCalculatedProperty, prop))
    graph.add((prop, RDFS.label, Literal(propertyname)))
    graph.add((prop, EX.hasValue, Literal(value)))
    if units is not None:
        graph.add((prop, EX.hasUnit, URIRef(f"http://qudt.org/vocab/unit/{units}")))
    return graph

def get_inputs_and_outputs(node):
    inputs = parse_input_args(node.node_function)
    outputs = parse_output_args(node.node_function)
    if isinstance(outputs, dict):
        outputs = (outputs, )
    return inputs, outputs

def add_outputs(graph, node, EX=EX):
    inputs, outputs = get_inputs_and_outputs(node)
    for key, out in zip(node.outputs.labels, outputs):
        if out["triple"][0] == "isAssociatedWith":
            sample, graph = create_node(graph, out["triple"][1], EX.ComputationalSample)
            graph = add_calculated_quantity(graph, sample, key, node.outputs.__getattr__(key).value, out["units"])
    return graph
```

# User definition
```python

from pyiron_workflow import Workflow
from semantikon.typing import u
from ase import Atoms, build

structure = build.bulk("Al", cubic=True)

@Workflow.wrap.as_function_node
def get_volume(structure: Atoms) -> u(float, label="volume", units="angstrom**3", triple=("isAssociatedWith", "structure")):
    volume = structure.get_volume()
    return volume

node = get_volume(structure=structure)
node.run()
```

# Parsing

```python
g = Graph()
g = add_outputs(g, node)
```

## Comments

- It's largely copied and pasted from [atomRDF's `graph.py`](https://github.com/pyscal/atomRDF/blob/main/atomrdf/graph.py) (Sarath was saying he'd be happy to offload the data extraction [here](https://github.com/pyiron/pyiron_ontology/issues/81), so I guess it's ok)
- I basically reserved the term `isAssociatedWith` for anything related to a sample, which is in line with atomRDF's `associate_to_sample`.
- I did something very different from what I had said in my comment above: I simply say the structure is called `structure`, which does not have to do anything with the actual input structure. I saw the advantage that the user does not have to worry about what the variable is actually called throughout the workflow, because it would associate with the same label as long as it does not change. Not sure if that's a sensible thing to do. What do you think? @liamhuber 


## Knowledge graph of the above graph

<img width="1275" alt="Screenshot 2024-12-18 at 22 43 16" src="https://github.com/user-attachments/assets/4d70e266-254a-4de6-9a42-170b7aca11aa" />

**Comment by liamhuber** [comment]
> Currently, we don't have a way to tell how inputs and outputs are ontologically connected

Probably good to be careful with your context here. Currently, we _do_ have a way to do this, it's right there in the examples and you explicitly say "this is input of that", "this is output of the other", etc. But I guess what you mean is that in our renewed attack on the topic we haven't yet settled on an approach to couple these things.

**Comment by liamhuber** [comment]
> ```python
> def get_inputs_and_outputs(node):
>     inputs = parse_input_args(node.node_function)
>     outputs = parse_output_args(node.node_function)
>     if isinstance(outputs, dict):
>         outputs = (outputs, )
>     return inputs, outputs
> ```

On a technical note, we're going to want to be scraping the o-info (and data type hints) from the `node.io_preview()`, which is available at the class level for _all_ non-`Workflow` nodes. Relying on `.node_function` means the implementation will only work for `Function` nodes and not for macros, dataclass nodes, etc.

**Comment by samwaseda** [comment]
Since now we started a larger discussion [here](https://github.com/pyiron/pyiron_ontology/issues/85), and I also made it super messy here, I'm gonna close this issue.
